services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../sandbox:/opt/game:ro
      - ../carimbo/build:/opt/engine:ro
  redis:
    image: redis:latest
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 9
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - storage:/data

volumes:
  storage: