[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["F", "I"]

[tool.ruff.lint.isort]
force-single-line = true

[mypy.plugins.mypy_django_plugin]
main = true

[mypy.plugins.django-stubs]
django_settings_module = "gatekeeper.settings"
